### ISSUE TITLE
Row header, taller cell

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#10]
The first row of the tables that has blue background colour needs to be taller. The high of the this first row is a bit more than the high of the titles. We need at least another blank space.

**Comment by jpradocueva** [comment]
@nathan-omaorg, @jmudge, @seanmcilroy29 .
It is not possible to allocate an issue to a multiple milestones. This means that e.g. this problem needs to be raised on each milestone or template page.

**Comment by nathan-omaorg** [comment]
I've added some padding to the table header.

If this isn't the correct amount, feel free to adjust to how you want it in the Site.css under the following selector:
table > thead > tr > th: 1em; (change the 1em to a lower number to adjust the amount of padding on all table headers)
