### ISSUE TITLE
File OMA-OIDs.asn cannot be downloaded

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#104]
When an attempt is made to download the following file from the dev web site the error message "Server Error 404 - File or directory not found." is generated:
http://devwww.openmobilealliance.org/tech/omna/OMA-OIDs.asn

Perhaps the filetype asn is configured to be not allowed to be downloaded by the web server.

**Comment by nathan-omaorg** [comment]
Is this a similar issue to the .ac files?

Do you know what a .asn file is used for and are we sure that this is the correct extension?

@seanmcilroy29 and @jpradocueva, is this okay?

Thanks,
Nathan

**Comment by jmudge** [comment]
> Is this a similar issue to the .ac files?
> 

Yes I believe so.

> Do you know what a .asn file is used for and are we sure that this is the correct extension?

They are Abstract Syntax Notation One (ASN.1) formatted files. The extension is what is currently used on the public website for such files.

**Comment by nathan-omaorg** [comment]
I've updated the mime types
