### ISSUE TITLE
Pull request 100, 102, 103

### ISSUE THREAD

**Issue by nathan-omaorg** [OpenMobileAlliance/openmobilealliance.github.io#105]
For pull request: https://github.com/OpenMobileAlliance/openmobilealliance.github.io/pull/102

- bcast-client-manufacturer-code-registry.html looks wrong
![image](https://cloud.githubusercontent.com/assets/20474446/18210515/cb46f9d8-7130-11e6-871e-29fb8b229e00.png)

- bcast-indentification-authority-registry.html looks wrong
![image](https://cloud.githubusercontent.com/assets/20474446/18210509/bfc13c2c-7130-11e6-9e44-ad838fe66b70.png)

- For any files that is a copy and paste from the existing registries (i.e. using DIVs instead of TABLE for layout), please remove: <script src="/Scripts/LwM2MRegistry.js"></script> from the HEAD

- Make sure you use the following template for the copied information from existing registries: /OMNA/wsp/RegistryTemplate.html

**Comment by seanmcilroy29** [comment]
Header updated to resolve registry look
