### ISSUE TITLE
Connect each registry with its corresponding registry form

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#106]
Inside of most of the registries there is a link called 'here' that needs to be connected with the corresponding registry. At the moment the link 'here' opens a form to submit registration information.

**Comment by nathan-omaorg** [comment]
I need an example of which registry and where in the page (a screenshot would be useful. Use the snipping tools. Copy and paste works in Github comments)

Thanks

**Comment by jpradocueva** [comment]
This link 'here' 
![here](https://cloud.githubusercontent.com/assets/3258579/18255039/c96ffd32-7359-11e6-88c2-3b103cf57ae4.png)

that link needs to be connected to the page: 
![content](https://cloud.githubusercontent.com/assets/3258579/18255101/800dd3f2-735a-11e6-9aed-882b92891aca.png)

**Comment by seanmcilroy29** [comment]
All links updated to point to the register page. Issue can be closed
