### ISSUE TITLE
Technical Menus

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#11]
#14 @nathan-omaorg, @jmudge, @seanmcilroy29 
Final list of menus in the Technical Menus:

* "Specifications", (file is called index.html)
* "Pubic Documents"
* "Supporting Data"
* "Registries"
* "Comments"
* "Watch/Unwatch" 
* "Developer's"
 
The OMA icon is connected to the OMA Marketing homepage.
This final list was produced after discussions with the Marketing Manager

**Comment by jmudge** [comment]
If the marketing menu will not appear in the technical pages (from https://github.com/OpenMobileAlliance/openmobilealliance.github.io/issues/19) then we could consider adding some of the marketing menu items to the technical pages e.g. Developers.

**Comment by jmudge** [comment]
Developers has now been added to the above list

**Comment by nathan-omaorg** [comment]
Please can the mockups be updated with the new Developers menu.

Thanks

**Comment by nathan-omaorg** [comment]
I have created the developers menu. It just needs the subtext to be added.
