### ISSUE TITLE
wsp_content_type_codes.html - not all text is displayed

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#125]
On page https://openmobilealliance.github.io/OMNA/wsp/wsp_content_type_codes.html in the Registered Values table some of the test content in the last column is not displayed e.g. for Assigned Number 0x0300. Please note that this is also true (but to a lesser extent) with the current production page at http://technical.openmobilealliance.org/Technical/technical-information/omna/omna-wsp-content-type .

**Comment by nathan-omaorg** [comment]
Hi John,
None of those links work. Can you please give me a link with a screenshot to help me find where you're referring to.

Thanks

**Comment by jmudge** [comment]
Now that the pages are in production on the Microsoft IIS web-server the URL of the page is:
http://www.openmobilealliance.org/wp/OMNA/wsp/wsp_content_type_codes.html

**Comment by seanmcilroy29** [comment]
Page has been updated to a larger column
