### ISSUE TITLE
Tables on some registry pages are not aligned on the far right hand side

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#126]
On some of the registry pages the table headers, rows and dashed lines are not aligned on the far right hand side e.g. https://openmobilealliance.github.io/OMNA/wsp/wsp_content_type_codes.html .

This is also the case (but to a lesser extent) with the current production pages e.g. http://technical.openmobilealliance.org/Technical/technical-information/omna/omna-wsp-content-type

**Comment by seanmcilroy29** [comment]
Registry headers updated
