### ISSUE TITLE
Please add access to rename files in devwww via ftp

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#152]
I am unable to rename the following incorrect folder name via ftp:

http://devwww.openmobilealliance.org/release/LWM2M_PortfolioObj/OMA-RRP-LWM2M_PortfolioObj-V1_0-20160906-C

I can upload files via ftp, please add permissions to rename (and also delete files if necessary).

**Comment by seanmcilroy29** [comment]
I've updated the ftp to rename the folder
