### ISSUE TITLE
Create new folder under the root folder "omna"

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#16]
The registry will required the creation of new folders in the github repository.
* the registries.html page will be stored in the root folder
* "omna" folder needs to be created and stored in the root folder.
   * the "omna" folder will contain several folders inside. One folder for each register. And each of these folders will contain one or more html pages.

**Comment by nathan-omaorg** [comment]
I have created the OMNA folder and put the LwM2MRegistries.html file /OMNA/LwM2M/
