### ISSUE TITLE
Problems with LwM2M Registry tables

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#164]
I see the following problems in the file "LwM2MObjects.html":

**OMA Label Table**
- [ ] The Object xml file are downloaded from the old FTP server instead from the new one,(devwww.openmobilealliance.org) 
- [ ] The LwM2M Editor file are also downloaded from the old FTP Server instead from the new one,(devwww.openmobilealliance.org)
- [ ] Object 2 in the editor column points to the wrong object
  There are a few inconsistencies in the links to the Objects and Editor columns, it needs to be reviewed.

**External Label**
- [ ] ObjectID column is missing url's to files
- [ ] Editor column the files are pointing to the old FTP server. Please note that in the new FTP server there is no a folder called "/IPSO/" this folder name has changed to "/lwm2"m/"

**x-Label**
- [ ] ObjectID column, some files are missing
- [ ] LwM2M Editor column, files here are pointing to the old FTP server
- [ ] There is an optional note at the end of the table. Is this needed? I don't recall to introduce this.

**Reusable Resources**
- [ ] ResourceID colum, is possible to find out the files for these resources?
- [ ] Resource Name column, if there is no file to download it should not be a link

**Comment by seanmcilroy29** [comment]
LWM2M objects has been updated as per the meeting requirements
