### ISSUE TITLE
Create a new folder "lwm2m" folder inside "oma" folder and a new template lwm2m.html

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#17]
We need to create a subfolder "lwm2m" inside of "oma" folder.
Inside "lwm2m" we need to create a new template "lwm2m.htm"
This template will contain the Technical Menu plus the tables listed in the spreadhseet "View Registry"

Also, in this template "lwm2m.html" we need to need to add:

* ```code block``` as seen in the above spreadsheet
* replace the icon (information) for the first line of the description

**Comment by nathan-omaorg** [comment]
Do you mean "OMNA" folder rather than "oma" for the lwm2m registry?

I will add "Registry" to the end of the html file name to make them more descriptive. i.e. "LwM2MRegistry.html"

And do these all need to be lowercase, or can I leave them uppercase? (this has very little impact either way)

**Comment by nathan-omaorg** [comment]
I have created the OMNA folder and put LwM2M in there for the time being.

Please reopen this issue if this isn't correct with where you'd like this registry to be.
