### ISSUE TITLE
Creation of an example of Row and column merge

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#18]
The link below contains an example of column and row merge.
You need to create a template containing a table that has this type of merges.

http://technical.openmobilealliance.org/Technical/technical-information/omna/omna-bcast-parental-rating-system-registry

**Comment by nathan-omaorg** [comment]
I have created an example at the following:
/Examples/RowandColumnSpanExample.html
