### ISSUE TITLE
Link to Terms of Use is not clearly visible

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#200]
When hovering over the "Terms of Use" at the bottom of the page in the footer, it is not clear that there is a link on "Terms of Use". 
I suggest even to extend the link to cover "Website Terms of Use" and make it clear that it is a link when hovering over. See look & feel of how the link is displayed in the current WordPress pages.

**Comment by seanmcilroy29** [comment]
I've updated the footer http://devwww.openmobilealliance.org/wp/registries.html so the 'Website terms of use' appears in another colour and i've also added a call out box 'Click to view Website terms of use'
