### ISSUE TITLE
Menu link doesn't work in github.io

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#201]
https://openmobilealliance.github.io/OMNA/LwM2M/supporting_data.html this link is giving a 404 response

**Comment by seanmcilroy29** [comment]
I can't find the location for that URL and no supporting file is associated LWM2M

The supporting data link is https://openmobilealliance.github.io/supporting_data.html

**Comment by jmudge** [comment]
From the page https://openmobilealliance.github.io/index.html the menu link for the "Supporting Data" is https://openmobilealliance.github.io/supporting_data.html and this URL works. What page contains the link that you have found?

Please note that the web pages at https://github.com/OpenMobileAlliance/openmobilealliance.github.io are not currently being maintained. The decision was made to instead use http://devwww.openmobilealliance.org/wp/
