### ISSUE TITLE
Affiliates links to Affiliates pages get back 404

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#203]
From http://devwww.openmobilealliance.org/wp/Affiliates.html page it is not possible to access each individual page for affiliates e.g. http://openmobilealliance.org/wp/Affiliates/LIF.html

**Comment by seanmcilroy29** [comment]
The links for the pages are currently being updated to prepare for the switch over. 
I've returned the links back to devwww. so you can view the page.
