### ISSUE TITLE
Problem with Marketing pages but raised here for visibility.

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#204]
The links in the below page (Marketing pages)  to Affiliates (HTML pages) need to be redirect.

http://openmobilealliance.org/about-oma/affiliates/

This is raised here to make sure that it does happen. I will raise this with Megan but she needs to be given the links in the HTML pages to redirect.

**Comment by seanmcilroy29** [comment]
Has been added to Project 'Things to do'

**Comment by seanmcilroy29** [comment]
To be updated by Elizabeth if required
