### ISSUE TITLE
Remove access to github.io pages

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#223]
Until we resolve how to view the new technical pages in github, we should remove the the https://openmobilealliance.github.io and redirect it to the new index page.

I believe that we can host the same html pages in GitHub but at the moment, it appears as broken links.

**Comment by nathan-omaorg** [comment]
I don't have access to do this. But if you go to the settings for the repository you can turn off the gh-pages: 

![image](https://cloud.githubusercontent.com/assets/20474446/21357266/7767754e-c6cc-11e6-9df8-6b3cc1fab7e8.png)

**Comment by github-oma** [comment]
@nathan-omaorg  ... interesting. In this repository, the selection that you are doing above was not available for me. It was not able to select the branch "gh-pages-branch".  I had to delete the link to the website in a different window.

**Comment by nathan-omaorg** [comment]
That's strange you have a different set of settings from my own repository. I wonder why?

Reading your comment it looks like you've found a way to do it. So I'll close the issue unless we need to looking into this more?
