### ISSUE TITLE
Incorrect redirect in Contact Us "Comments on Specifications"

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#228]
In Marketing Pages: http://openmobilealliance.org/contact-us/
Under Technical Contacts;  "Comments on Specifications" the "Technical Comments Form" http://technical.openmobilealliance.org/Technical/technical-information/comment-form, has to be mapped or find an alternative in the new html pages

**Comment by seanmcilroy29** [comment]
I'll contact Elizabeth to see if she's ok for me to update the Marketing pages

**Comment by seanmcilroy29** [comment]
I've updated the marketing page URL to point to http://www.openmobilealliance.org/wp/comments.html
