### ISSUE TITLE
Incorrect content in Marketing Pages TestFests

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#229]
http://openmobilealliance.org/oma_events/testfests/

The above page contains incorrect information.
- Keep the schedule but the rest of information may not be needed.

**Comment by seanmcilroy29** [comment]
This page is part of the Marketing Pages so this will need to be updated by Elizabeth or Megan

**Comment by seanmcilroy29** [comment]
I'll contact Elizabeth to see if i can make the updates
