### ISSUE TITLE
Add subtext to Developer menu item in header.html if necessary

### ISSUE THREAD

**Issue by nathan-omaorg** [OpenMobileAlliance/openmobilealliance.github.io#23]
See title

**Comment by jpradocueva** [comment]
@nathan-omaorg, @seanmcilroy29, @jmudge 
this has been rectified by adding the subtitle "Toolkit". Also, I have changed the colour and position of the Developer menu to aligned it with registries.
The change is already in my Branch Joaquin. We can keep this issue open until it is merged.
