### ISSUE TITLE
Update on ObjectID Classes for LwM2M

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#230]
In this link: http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html

We need the following updates:

**ObjectID Classes Table**
reserved category should be from 1024 to 2047  rather than 1024 20147

**x-label**
We need to split this range in two ranges:
1) 10241 - 26240 
2) 26241 - 32768
In the description column we need to add:
Objects Produced by Vendors
1)This range accepts registrations (Sean this is for the first range 10241 to 26240)
2) This range is privately reused and there is no need for registration.

As a result the range in: http://www.screencast.com/t/MQt43CDoxg  needs to be also split as:

"URN: urn:oma:lwm2m:x:ObjectID  | ranges (10,241 - 26,240) & (26,241 - 32,768)

Also, we need to add a clarification in the row "oma-label", in the column "Operations" the right side of the split column says ("--")  it should say "Reserved to OMA"

**Comment by seanmcilroy29** [comment]
LWM2M table updated with changes
