### ISSUE TITLE
Description column should be restricted to show only two lines

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#231]
In the past the description column in the registries i.e. http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#resources  was restricted to display only two rows of description.

Currently, it displays everything.

Is this because we try to use the information on these tables to be reuse by the Editor tool?

**Comment by seanmcilroy29** [comment]
Columns in the registry now only displays 2 rows
