### ISSUE TITLE
Link in TestFest page points to the wrong link

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#234]
In the technical pages "TestFest" the link in the TestFest page "When Is the next Testfest?" points to http://openmobilealliance.org/event/oma-testfest-schedule/  when in reality should point to: http://openmobilealliance.org/oma_events/testfests/ 

This comment is after having a discussion with Elizabeth and Megan on 20th Dec.

**Comment by seanmcilroy29** [comment]
Link updated
