### ISSUE TITLE
File OMA-OIDs.asn cannot be downloaded

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#238]
From the webpage http://www.openmobilealliance.org/wp/OMNA/security/iso_object_identifiers.html the following file cannot be downloaded:

http://www.openmobilealliance.org/Tech/OMNA/OMA-OIDs.asn

Has the Microsoft IIS server been configured to permit the download of files with the extension ".asn"?

**Comment by nathan-omaorg** [comment]
I have added .asn to the file types that can be downloaded
