### ISSUE TITLE
File dmapi-v1_0.widl cannot be downloaded

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#239]
From the webpage http://www.openmobilealliance.org/tech/profiles the following file cannot be downloaded:

http://www.openmobilealliance.org/tech/profiles/dmapi-v1_0.widl

Has the Microsoft IIS server been configured to permit the download of files with the extension ".widl"?

**Comment by nathan-omaorg** [comment]
I've added .widl to file types that can be downloaded.
