### ISSUE TITLE
Update readme.txt file for lwm2m

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#240]
The content of this file: http://www.openmobilealliance.org/release/LightweightM2M/README.txt

Needs to be updated with an explanation of how to find document in this folder.
We need to explain what does it mean and contain the following folders:
"ETS"
"EVP"
And a general description of the names of the technical documents folder, e.g. Version \ Year \ Month \ Day \ Status. And that the user should look for the folder with the last date to obtain the latest set of documents.

**Comment by jmudge** [comment]
Hasn't this README.txt file been superseded by:
http://www.openmobilealliance.org/wp/Overviews/lightweightm2m_overview.html

Do we need both the readme and the overview files?

**Comment by github-oma** [comment]
There are two different files.
Overview is a html file stored in github that can be under the control of the OMA Working Group. It can be used by marketing to target different audience.

Readme.txt file is stored in the ftp and it should be added to all the enablers explaining how to interpret the folders inside of the ftp. It may not be self-explanatory for the public what ETS or EVP means. And the name of the folders containing the documentation.

**Comment by seanmcilroy29** [comment]
.txt file updated with a general description of the technical documents folder, ETS, EVP & folder explanation
