### ISSUE TITLE
Update LwM2M Overview page

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#241]
In this page http://www.openmobilealliance.org/wp/Overviews/lightweightm2m_overview.html

We should add at the of the page the same link as we have at the bottom: "[Documents for download](http://www.openmobilealliance.org/release/LightweightM2M/)".

This is a navigation enhancement. The link should be on both parts of the document at the bottom and at the top.

**Comment by seanmcilroy29** [comment]
Link added
