### ISSUE TITLE
Can http://www.openmobilealliance.org/test_events/web.config be deleted?

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#246]
The page http://www.openmobilealliance.org/test_events references the following file:

http://www.openmobilealliance.org/test_events/web.config

If the file is clicked on it cannot be downloaded. Can the web.config be deleted? Does the file need to be located in this directory?

Similarly can the following file be deleted or moved?
http://www.openmobilealliance.org/tech/web.config

**Comment by nathan-omaorg** [comment]
Those files are necessary. But I have found a way to hide them from the directory browsing.
