### ISSUE TITLE
Can the “.svn” directories and files be deleted?

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#247]
There are alot of strange “.svn” directories in the filesystem, perhaps to do with an earlier OMA website.

Can these directories and associated files be deleted?

AFAIK we are not using these files.

**Comment by jpradocueva** [comment]
These directories are not from us, we need to cross check with Nathan.
I believe that are part of an old application used by Forapolis.

If this is the case, yes, I believe that we should be able to delete without any problem.
As a test we could just change the name of the directory. If there is anything using it will stop working and we will see some problems. If nothing happen we can delete them after a period of time.

**Comment by nathan-omaorg** [comment]
The .svn directories are related to subversion version control. It's not something we use so I think we can delete them.

I've removed the .svn directories from DEV: devwww.openmobilealliance.org.

If this hasn't caused any issues, then we can go ahead to remove them from PROD.

Have a look and let me know.

**Comment by jmudge** [comment]
I have done a quick check and have not noticed any problems with devwww.openmobilealliance.org

**Comment by nathan-omaorg** [comment]
I've also removed them from PROD
