### ISSUE TITLE
Rackspace 404 error page is not being displayed

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#248]
A blank page is bring displayed instead of the Rackspace 404 error page

**Comment by seanmcilroy29** [comment]
This is also affecting the rackspace system
@nathan-omaorg

**Comment by nathan-omaorg** [comment]
I have found a way to work around this.

Please try this out and let me know if it's suitable.

You can customise the 404 page inside the marketing Wordpress site to show whatever you'd like.
