### ISSUE TITLE
LwM2M Registry object 3310 is duplicated.

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#250]
In the LwM2M Registry page: http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html

Object 3310 is duplicated.
While the first 3310 object is correct, the second should be Object 3314, (Magnetometer). It appears that the links are correct, the only incorrect is the name of the object.

**Comment by seanmcilroy29** [comment]
Table updated
