### ISSUE TITLE
Add readme.txt files to the release folder in the ftp.

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#293]
We got a question about to find certain files in our ftp pages.
I believe that people may struggling to understand the image below: 

![ftp_view](https://cloud.githubusercontent.com/assets/3258579/22132441/e13e1e78-de6e-11e6-9a1b-be3124042ecd.png)

I believe that we need to insert http://www.openmobilealliance.org/release/LightweightM2M/README.txt file in each release folder. In this way, the user has a reference to interpret the content of the ftp folder.

**Comment by jmudge** [comment]
The file http://www.openmobilealliance.org/release/LightweightM2M/README.txt has been copied to each of the release folder.

This issue can be closed.

**Comment by jpradocueva** [comment]
Thanks John,

Joaquin
---------------------------------------
Director of Technical Programs
Open Mobile Alliance | www.openmobilealliance.org<http://www.openmobilealliance.org/>
Cell: (+1) 858 249 8300<tel:%28%2B44%29%20%280%2977%2017%2027%2050%2024>
Desk: (+1) 858 623 0741
Skype: jpradocueva
Email: jprado@omaorg.org<mailto:jprado@omaorg.org>
