### ISSUE TITLE
Link "Register Resources" in the Registry page still points to GitHub

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#294]
In this page http://www.openmobilealliance.org/wp/registries.html
Contains a link called "Register Resources" which points to https://github.com/OpenMobileAlliance/LwM2M_Register/blob/master/Register_Reusable_Resources.md instead to the future link in the LwM2M editor tool.

**Comment by seanmcilroy29** [comment]
Link updated
