### ISSUE TITLE
Incorrect URL for LwM2M 3-PhasePM.xml

### ISSUE THREAD

**Issue by scop** [OpenMobileAlliance/openmobilealliance.github.io#382]
DDF.xml and LwM2MObjects.html contain URL http://www.openmobilealliance.org/tech/profiles/3-PhasePM.xml (and the corresponding devtoolkit links) for 3-PhasePM.xml, but that link gives a 404 Not Found. A fix would apparently be to update the URLs to point to http://www.openmobilealliance.org/tech/profiles/lwm2m/3-PhasePM.xml (note the missing lwm2m subdir), or to move the file location up one level to the profiles/ dir on the openmobilealliance.org website where all other DDF files seem to be located.

**Comment by jmudge** [comment]
Thank you very much for pointing this out. The issue has now been resolved and the URL http://www.openmobilealliance.org/tech/profiles/3-PhasePM.xml now works.
