### ISSUE TITLE
Technical Menu needs to be centered in the page

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/openmobilealliance.github.io#39]
The top technical menu appears to be on the left of the screen rather than in the center as the rest of the content.

**Comment by nathan-omaorg** [comment]
What is the technical menu?

**Comment by jmudge** [comment]
On the web page https://openmobilealliance.github.io/ directly below the OMA logo in the top left hand corner it is the menu beginning "Specifications Technical Documents" ...

**Comment by nathan-omaorg** [comment]
Done in DevMaster
