### ISSUE TITLE
Add a link to "Affiliates" specifications from this page

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/openmobilealliance.github.io#40]
@jmudge, @seanmcilroy29 
As the "Affiliate" page has been moved under the Marketing pages.

**Comment by jmudge** [comment]
Is this link required to be added to the menu on all the technical web pages?

What will the URL of the new marketing affiliates web page be?

**Comment by github-oma** [comment]
The way I visualize the implementation of "Affiliates" information is as follow:
* the page containing all the organizations can be kept as now but it is moved to the marketing pages
* when you link in a particular organization it opens a ftp view in the new ftp server.
* We may need to consider to add a readme file for each organization
* from the "Specifications" page we should have a link in the first paragraph (introduction). I don't visualize that we need to add the link "Affiliates" in the Technical Menu Header. Otherwise, we will have to expand again the Technical Menu with all the links that we are moving to the Marketing pages.

**Comment by jmudge** [comment]
The current URL for the Material from Affiliates web page is http://technical.openmobilealliance.org/Technical/technical-information/material-from-affiliates . Elizabeth will have to tell us what the new URL will be.

Some of the web pages have links to multiple directories e.g. 
http://technical.openmobilealliance.org/Technical/technical-information/material-from-affiliates/wap-forum

I expect that the multiple directories could be included in the affiliates web page.

Can the terms of use agreements can be removed? E.g. http://www1.wapforum.org/tech/terms.asp? and http://technical.openmobilealliance.org/Technical/use-agreement . Do we need to check with anyone about them?

**Comment by seanmcilroy29** [comment]
Affiliates page has been updated (Mock-up http://openmobilealliance.org/about-oma/affiliates-2/ ).
Once we go live we can revert to the attached mock-up

**Comment by jmudge** [comment]
Additional links to other directory trees may also need to be provided e.g.
- http://www1.wapforum.org
- http://www.wapforum.org (especially http://www.wapforum.org/DTD & http://www.wapforum.org/xslt)

**Comment by jmudge** [comment]
In index.html added link to Affiliates web page in Pull request #53 https://github.com/OpenMobileAlliance/openmobilealliance.github.io/pull/53
