### ISSUE TITLE
Links to devwww ftp server

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#42]
@jmudge I am checking the links to the new http://devwww.openmobilealliance.org/tech/dtd and when upload it to a browser,  it opens the ftp server rather than redirect but in your page "Supporting Data" it is redirected as we see on Tuesday.

It is something strange, could you check it again?

**Comment by jmudge** [comment]
The links on the Supporting Data web page are all fine, however the presence of the index files in the devwww.openmobilealliance.org ftp directories seems to be triggering the unwanted redirects. The index files in the relevant directories have been moved/deleted and the web page works fine.
