### ISSUE TITLE
Consider  using XSD Schema Definition for the DDF.xml and common.xml files

### ISSUE THREAD

**Issue by nathan-omaorg** [OpenMobileAlliance/openmobilealliance.github.io#425]
I would highly recommend that you look into setting any of the XML files to also use XSD schemas to help with maintenance, consistency and validation.

Have a look here to see how to set this up if you don't know already:
https://www.w3schools.com/xml/schema_intro.asp

Also note that the XSDs can be version numbered so that older versions of the XML files will still be valid for their versions of the XSDs.

**Comment by jpradocueva** [comment]
An schema has been added to both DDF.xml and Common.xml files.
