### ISSUE TITLE
A Vorto link in the DDF.xml for L2M2M needs adding

### ISSUE THREAD

**Issue by nathan-omaorg** [OpenMobileAlliance/openmobilealliance.github.io#434]
The Vorto data needs to be split into 2 parts in the XML:

1 . Vorto Identifier
2. Vorto Link URL

This could be done either as an XML attribute or as 2 separate XML elements.

**Comment by jpradocueva** [comment]
@nathan-omaorg, @seanmcilroy29 
Do you really think that we need a Vorto Identifier?
Without doing a deep investigation, I would think that it is possible to reuse "ObjectID" to provide the "word" that host the Vorto link "Vorto". The ObjectID value is the name of the Vorto object too.
If this is possible then we don't need to introduce a new element or attribute to hold the name of the Vorto Object. 
If this is a feasible solution, then cross check it with Svante to make sure that his tool and the API will work ok.

**Comment by jpradocueva** [comment]
A vorto identifier was added to the DDF file and schema.
