### ISSUE TITLE
Do we need to maintain the copyright click to obtain docs.

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#45]
Currently, to download documents from the affiliates it is necessary to accept a copyright.
Do we need to maintain this copyright in the new publication system?

**Comment by seanmcilroy29** [comment]
From all the associated Affiliate pages there is no longer a requirement to accept the copyright.

**Comment by github-oma** [comment]
@seanmcilroy29  Let's to keep this open until I discuss this with Seth.

**Comment by jpradocueva** [comment]
It was not needed to have a copyright disclaimer.
