### ISSUE TITLE
Enhance table titles with reference to download xml and TS docs.

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#46]
Table titles in the lwm2m registry page needs an enhancement: see a possible way to do it below
oma-label, ext-label, and x-label tables.
"Object ID" change it to  "Object ID / xml"
"Object Name" change it to "Object Name / Specifications"
"Resource ID" change it to "Resource ID / xml"

Reusable Resources Table
"Resource Name / DDF" change it to "Resource Name / xml"
"Owner / TS"  remove the "TS"

**Comment by seanmcilroy29** [comment]
Table titles updated in latest pull request

**Comment by seanmcilroy29** [comment]
Add to pull request #52
