### ISSUE TITLE
Remove link from registration of Objects by vendors or individuals

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#47]
Remove the link in the paragraph at the bottom of the (x-label). Keep the phase as seen below but remove the link. The reason for that is because there is still a pending discussion in DM if OMA really needs to register: individuals or vendors Objects. In the GitHub repository for LwM2M Register we haven't created any register for this option.

"The registration of individual and proprietary LwM2M Objects is currently under review."

**Comment by seanmcilroy29** [comment]
Link has been removed for the Register a new resource produced by 3rd parties.

**Comment by seanmcilroy29** [comment]
Add to pull request #52

**Comment by jpradocueva** [comment]
This was updated in Pull Request #69
