### ISSUE TITLE
DevMaster OMA Specifications page one line of release notes

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#5]
@nathan-omaorg 

On DevMaster OMA Specifications page in the right hand column I understand there is only expected to be one line of release notes now. This could be aligned vertically with the Version number. 

See the mockups at SyncIT > Projects > Publication > Mockups-v2.xlsx

**Comment by nathan-omaorg** [comment]
You can make as few or many lines as you want. The multi-line comment is there just to show that you can do it if you want to. So when it comes time to you filling these templates in, just add the notes as you want.

**Comment by jmudge** [comment]
@nathan-omaorg

The DevMaster OMA Specifications page in the right hand column does not fully match the corresponding Mockup page. The Version number is not vertically centered with the Historic text. In fact the Historic text is displaying partially above the Version number (see example at https://jmudge.github.io/openmobilealliance.github.io/index.html).

Also see the mockups at SyncIT > Projects > Publication > Mockups-v2.xlsx

**Comment by jmudge** [comment]
Currently when the width of the browser window that the DevMaster OMA Specifications page is displaying in is reduced then the "Historic" text overwrites the version number. Instead the "Historic" text could be a suffix of the version text string; in red with the same sized font.

**Comment by nathan-omaorg** [comment]
I have added the option to do this in the index.html template.

Have a look, and if it's suitable, use that instead of the other options. (it's using a <span> inside of the <a> to style the text)
