### ISSUE TITLE
LightweightM2M V1.0 Overview is not displaying properly

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#511]
The following web page is not displaying properly:
http://openmobilealliance.org/wp/Overviews/lightweightm2m_overview.html

**Comment by seanmcilroy29** [comment]
What problems are you encountering as this page is displaying correctly for me?

**Comment by jmudge** [comment]
Try http://openmobilealliance.org/wp/Overviews/lightweightm2m_overview.html 
http://www.openmobilealliance.org/wp/Overviews/lightweightm2m_overview works

**Comment by seanmcilroy29** [comment]
Link updated in the code with www. and now appears to be working correctly
