### ISSUE TITLE
Missing links in the WAP page

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#58]
Links within the WAP forum current pages that are not listed inside of the FTP. 
http://www1.wapforum.org
http://www.wapforum.org 

These two are included in the above webpages:
(especially http://www.wapforum.org/DTD & 
http://www.wapforum.org/xslt)

The current mockup page http://openmobilealliance.org/about-oma/affiliates-2/ is missing the above links.

**Comment by jmudge** [comment]
Additionally there are links from registry pages to these areas.

**Comment by seanmcilroy29** [comment]
Links added
