### ISSUE TITLE
DevMaster OMA Specifications page LH column second line of cell’s contents

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#6]
@nathan-omaorg

On DevMaster OMA Specifications page in the left hand column the second line of a cell’s contents needs to use a smaller sized font and not be in bold.

See the mockups at SyncIT > Projects > Publication > Mockups-v2.xlsx

**Comment by nathan-omaorg** [comment]
Fixed in latest DevMaster
