### ISSUE TITLE
Split content inside LwM2MRegistry 

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#60]
We need to reuse the tables that display Objects and Resources in the LwM2M Editor Tool.
Suggestion:
Create a new file (LwM2MTables) which stores the tables that contain objects and embed that content in the LwM2MRegistry.

In this way we can reuse the LwM2MTables page in the LwM2M Editor tool without having to replicate this content over and over.
See Mockups-V5.xlsx spreadsheet in the syncfolder/projects/publication

**Comment by nathan-omaorg** [comment]
The LwM2M content has been separated into it's own file.
