### ISSUE TITLE
In LwM2MRegistry.html most top level menu links do not work

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#62]
In the OMA LightweightM2M (LwM2M) Object and Resource Registry web page (see https://openmobilealliance.github.io/OMNA/LwM2M/LwM2MRegistry.html)

The following top level menu links do not work:
- Specifications
- Public Documents
- Supporting Data
- Registries
- Comments

**Comment by nathan-omaorg** [comment]
Done in DevMaster
