### ISSUE TITLE
Error when attempting to download .mod files

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#63]
From web page http://devwww.openmobilealliance.org/tech/dtd/ when an attempt is made to download file with the extension mod the following error is displayed:

"Server Error
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable."

Note these files can be downloaded from the production web server.
E.g.
http://www.openmobilealliance.org/tech/DTD/wml-framework-1.mod - works
http://devwww.openmobilealliance.org/tech/dtd/wml-framework-1.mod - does not work

**Comment by jpradocueva** [comment]
@jmudge I have classified this issue inside of the Supporting_Data Menu

**Comment by jpradocueva** [comment]
Same problem happens for (.ddf) files. 
Also we nee to verify if there is any other type that is not displayed.

**Comment by jmudge** [comment]
The file http://devwww.openmobilealliance.org/tech/omna/Presence-v1_0.ac also cannot be downloaded. However I'm unsure that that ac file should be located there anyway with the file extension .ac - perhaps @jpradocueva could advise?

**Comment by github-oma** [comment]
I don't think that the extension (.ac) makes sense to any editor or browser. This file should have the extension of (.txt) as it is not an xml doc.
I believe that it is related to: http://www.openmobilealliance.org/tech/omna/dm-ac/ac_ap0002_presence-v1_0.txt but I don't know why it appears with that name. We will need to find the html page where the doc is listed and see if we can find out why appears with that name.

**Comment by nathan-omaorg** [comment]
I have updated the IIS site so the mime types for .dtd, .ddf and .mod are application/octet-stream. This means that browsers will interpret them as files to download.
