### ISSUE TITLE
LwM2M registry, supporting data and affiliates navigation

### ISSUE THREAD

**Issue by nathan-omaorg** [OpenMobileAlliance/openmobilealliance.github.io#7]
Where will the links to the following pages be?

- LwM2M registry
- Supporting data
- Affiliates

I don't see them in the menu or elsewhere.

Thanks

**Comment by jmudge** [comment]
The Registries page and the OMA Specifications page include links to the LwM2M registry.

There is a top level menu entry for Supporting Data., in addition to links on the OMA Specifications web page.

The SyncIT file Mockups-v2.xlsx Release Program tab includes the sub menus. The About OMA sub menu has a link to Affiliates.
