### ISSUE TITLE
Which repository to use to read from the DDF?

### ISSUE THREAD

**Issue by nathan-omaorg** [OpenMobileAlliance/openmobilealliance.github.io#727]
Which repository will become the defacto one for LwM2M? I need to change this in the script that builds the tables from the DDF.xml.

Thanks

**Comment by jpradocueva** [comment]
The repository for the OMNA LwM2M Registry is: https://github.com/OpenMobileAlliance/lwm2m-registry
For the time being the development branch is called: "development" and the publication is called "master". 
These names will change once the last PRs are merged.

**Comment by nathan-omaorg** [comment]
Ok, I will update the reverse proxy rules to this repository when we go live
