### ISSUE TITLE
Many occurrences of "_vti_cnf" folders

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#73]
In the http://devwww.openmobilealliance.org/release/ directories there are many occurrences of the folder "_vti_cnf" e.g. http://devwww.openmobilealliance.org/release/DiagMon/V1_2-20131008-A/_vti_cnf/

Apparently these folders are created automatically by the FrontPage, Dreamweaver and Expression web. Are we currently using any of these programs (I'm not)? I noticed Carol using Dreamweaver a few years ago.

Opinion seems to be divided on whether "_vti_cnf" folders should be deleted. I would suggest that we delete them all before we go live with the new web pages.

**Comment by nathan-omaorg** [comment]
I checked up on that a while ago when we were doing the consolidation and came across the same sorts of information. Seems to be that there is some risk of removing them, but also may not affect anything and would allow us to clean things up.

It's up to you if you would like me to go ahead and do that. I can make backups of what we currently have, which would mitigate the risk. But there will be still be some risk of things breaking even so.

Let me know what you'd like me to do.

**Comment by github-oma** [comment]
@nathan-omaorg, @jmudge  will be the risk restricted to the folder that it contains these sub-folders? 
If it is yes, then less pick up a folder in the devwww ftp and delete it and see what is the problem.
The current production FTP shouldn't be modified by deleting any stuff.

**Comment by jmudge** [comment]
I'd suggest removing the "_vti_cnf" folders from the http://devwww.openmobilealliance.org/release/ directories.

**Comment by jmudge** [comment]
There are about 1450 of these "_vti_cnf" directories. It would be best to use a batch file or some other scripting language to delete them and their contents. @nathan-omaorg what would you suggest?

**Comment by nathan-omaorg** [comment]
I have run the script on devwww.openmobilealliance.org.. Please have a look and let me know if that's still all as you expect it to be (minus the _vti_cnf directories).

If so, then I'll run the same on PROD.

Thanks

**Comment by jmudge** [comment]
Some of the "_vti_cnf" directories have been removed, but it seems not all. For example devwwwftp.openmobilealliance.org/release/REST_NetAPI_ACR/V1_0-20130305-C/_vti_cnf is displayed in an ftp tool.

**Comment by nathan-omaorg** [comment]
This should be done now. Please try again.
