### ISSUE TITLE
RDs and ADs need to be moved into the release area

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#74]
There are RDs and ADs in the following folders that need to be moved into the release area:

- http://devwww.openmobilealliance.org/old-Technical/Release_Program/docs/RD
- http://devwww.openmobilealliance.org/old-Technical/Release_Program/docs/Arch

**Comment by jmudge** [comment]
All 80 RDs and ADs have been moved to the correct directories.

**Comment by seanmcilroy29** [comment]
All been moved
