### ISSUE TITLE
Investigate files that have .ac as an extension

### ISSUE THREAD

**Issue by nathan-omaorg** [OpenMobileAlliance/openmobilealliance.github.io#75]
There are some files with .ac as an extension that may need to have .txt instead.

Such as:  http://devwww.openmobilealliance.org/tech/omna/Presence-v1_0.ac

This was originally brought up in issue #63

**Comment by github-oma** [comment]
Guys, we need to make an assessment of this one.
First I will try to find how many files in our ftp server has this extension.

**Comment by github-oma** [comment]
I have done a search of all the folders in the devwww FTP. 
I have found only one file, /tech/oma/Presence-v1_0.ac. 
In the Support File guidelines: https://member.openmobilealliance.org/ftp/rel/P-N-G/SupportFiles_AC.shtm clearly indicates that these files should be with the extension (.txt). 
I believe that it is safe to delete this file and if there is any link point it to it then we will need to redirect to the equivalent file; which by looking to PRESENCE has a different name.

@jmudge any views?

**Comment by jmudge** [comment]
Presence Simple 1.0, when it reached final Approval, included OMA-SUP-AC_Presence_SIMPLE-V1_0-20060725-A and OMA-ERELD-Presence_SIMPLE-V1_0-20060725-A . Both these files indicate that the published AC file is http://www.openmobilealliance.org/tech/omna/Presence-v1_0.ac , this is the reason the file is in its current location.

Presence Simple 1.0 was later revised to Presence Simple 1.0.1 that has subsequently been made Historic.

When releases are superseded and made Historic we leave all the files in place.

I notice that, although the file Presence-v1_0.ac is still in the filesystem, the following URL does not currently work:
http://www.openmobilealliance.org/tech/omna/Presence-v1_0.ac

I'm not aware of any complaints that this URL is no longer working.

**Comment by jmudge** [comment]
After discussion in call on 24/8/16 the file "Presence-v1_0.ac" has been renamed to "Presence-v1_0.txt" and left in the same omna directory.
