### ISSUE TITLE
Add styling to content copied from current registries

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#79]
In the following web pages:
OMAN/wsp/wsp_content_type_codes.html 
OMAN/wsp/wsp-extended-methods.html
OMAN/wsp/wsp-header-code-page-names.html
OMAN/wsp/wsp-header-parameters.html
we pasted the content from the current registries: http://technical.openmobilealliance.org/Technical/technical-information/omna
We need to apply the corresponding styling to render the content correctly. If it is possible then, we will copy and paste the content from the rest of the registries and apply the corresponding styling.

**Comment by nathan-omaorg** [comment]
I have figured out how to get the styling done for this.

See the updated registries to get the general idea. All you have to do is the following:

1. Include the style sheets as seen in the code
2. Put the copied content into a <div class="container"> element (just after the header and close it just before the footer. Again, see the code for an example)
