### ISSUE TITLE
Specification page (the file is called 'index.hmtl')

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#8]
See mockups in spread sheet

1. Column titles should be in the center of the column
2. The declaration of "Historic" in the 3rd or 4th column should be part of the link e.g. "V1.0 - Historic"
    Where "Historic" is in red font.

**Comment by nathan-omaorg** [comment]
I have added the option in the index.html template to show what you would do if you want the Historic to be part of the link.

I've left all the other options in for where you would want to put extra notes so you can choose which one you want to go with.

Feel free to pick the method you prefer and go with that.
