### ISSUE TITLE
When clicking "Comment(s)" "present user with a similar statement as in Technical Comments

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#80]
When submitting a Technical Comments, the form currently provides the following Terms and Conditions:

"I am the sole owner of the information which I provide to OMA ('Submission') and have the authority without any restrictions to submit such information. The Submission is not confidential and contains no intellectual property rights ('IPR'). In the event that there were any IPR related to the Submission, I hereby grant to OMA and its members (present and future) a payment-free, royalty-free, perpetual, irrevocable, non-exclusive, worldwide license to use such IPR in any manner for any reason."

Comments is being access via at least two different type of links: from "Specifications" page and directly in from the technical menu.
We need to introduce a page or system that the user needs to accept before sending the email.
@jmudge  Could you please prepare a plan on what and how to do it?

**Comment by jmudge** [comment]
This is an example of where it is good to have well defined requirements.

If it is a mandatory requirement that non OMA members have to agree to this legal text before submitting any technical comment to OMA then I believe there would be the following impacts:
-	We can no longer accept any technical comments emailed direct to the Helpdesk.
-	We can also no longer accept any technical comments emailed direct to the TECHNICAL-COMMENTS email list.
-	We can not accept technical comments submitted to the GitHub repositories (e.g. as issues) from non OMA members, such as the repository OpenMobileAlliance/OMA_LwM2M_for_Developers.

It would be beneficial to have consistent requirements and policy across all the mechanisms that can be used by non OMA members to submit technical comments to OMA; not just replicate the different inconsistent approaches used today.

**Comment by github-oma** [comment]
Ok, let's tackle one by one starting with the email then the rest of the list.

* [ ] Define a system to allow add terms and conditions disclaimer when submitting an email to the helpdesk
* [ ] Define a system to allow add terms and conditions when submitting a comment  to GitHub Issue
* [ ] Define a system to allow add terms and conditions when submitting a comment to Jira

**Comment by jmudge** [comment]
> Define a system to allow add terms and conditions disclaimer when submitting an email to the
> helpdesk
> Define a system to allow add terms and conditions when submitting a comment to GitHub Issue
> Define a system to allow add terms and conditions when submitting a comment to Jira

I understand that there is no longer a requirement for these.

Can this issue therefore be closed?

**Comment by jpradocueva** [comment]
Yes, please go a head and close it.
Txs

Sent from my iPhone

On Sep 2, 2016, at 6:08 PM, John Mudge <notifications@github.com<mailto:notifications@github.com>> wrote:


Define a system to allow add terms and conditions disclaimer when submitting an email to the
helpdesk
Define a system to allow add terms and conditions when submitting a comment to GitHub Issue
Define a system to allow add terms and conditions when submitting a comment to Jira

I understand that there is no longer a requirement for these.

Can this issue therefore be closed?
