### ISSUE TITLE
The Description column in the "LwM2MObjects" page is broken

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#88]
Previously it was possible to see  at least two lines and click on  "more" to see the rest of the description.
Since we split the content of the original page: in "LwM2MRegistry" and "LwM2MObjects" this functionality of view just two lines of the description stopped working.

**Comment by nathan-omaorg** [comment]
I've changed the order that the DOM elements load so that the scripting will be applied at the correct time.

The line in question is:
$('#LwM2MObjects').load("LwM2MObjects.html", function () { SetUpExpandableTDs(); });
