### ISSUE TITLE
Registries pages name should not have blank spaces

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/openmobilealliance.github.io#90]
@seanmcilroy29 
It is a good practice to don't name file names with blank spaces or event capital letters.
e.g. currently "BCAST Service Class Registry.html" 
it should be called something like: "bcast-service-class-registry.html" 
@jmudge may be able to provide you with even better rules
The reason for these rules is to improve how the links are encoded by the browser, sometimes they need feel the blank space with some characters.

**Comment by seanmcilroy29** [comment]
Spaces have have been removed
