### ISSUE TITLE
Produce template that colours columns instead of rows

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/openmobilealliance.github.io#93]
Many of the registries use rowspan e.g. http://technical.openmobilealliance.org/Technical/technical-information/omna/omna-schema-based-namespace-registry . Displaying rows with alternating colours does not work well for these registries. If @nathan-omaorg added an option to alternate the colour of columns instead then this would help resolve this issue.

**Comment by nathan-omaorg** [comment]
I have made it so that if a table has a rowspan, the columns will be coloured instead of rows.

As long as /CSS/tabledregistries.css is included.

The change has been merged with DevMaster.
